Repository FTCLib/FTCLib, pull requests merged in 2020-11, with the labels that each got.

#114 Change Version in Gradle to v1.2.0
  core/build.gradle
  core/src/main/java/com/arcrobotics/ftclib/command/PrintCommand.java
  core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java
  core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorEx.java
  examples/build.gradle
  readme.md
Labels: internal

#110 Pulled from dev branch and readded changes
  core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGAdvancedHighGoalPipeline.java
  core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGAngleHighGoalPipeline.java
  core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGBasicHighGoalPipeline.java
Labels: enhancement

#130 MotorEx Velocity Hotfix
  core/build.gradle
  core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorEx.java
  readme.md
Labels: bug
