Repository FTCLib/FTCLib, pull requests merged in 2022-02, with the labels that each got.

#204 fix: set last state before current state
  core/src/main/java/com/arcrobotics/ftclib/gamepad/TriggerReader.java
Labels: bug

#203 Update Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: internal

#210 Update Kotlin Version
  build.gradle
  core/build.gradle
  core/vision/build.gradle
  examples/build.gradle
Labels: feature, internal

#211 Remove Acceleration from RevIMU
  core/src/main/java/com/arcrobotics/ftclib/hardware/RevIMU.java
Labels: feature, hardware, improvement
